// lib/quizzes/acpi-general.ts
// Quiz sobre la Tecnicatura en Automatización y Control de Procesos Industriales (ACPI)
import { Question } from "../questions";

export const ACPI_GENERAL_QUESTIONS: Question[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // AUTOMATIZACIÓN Y CONTROL INDUSTRIAL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 101,
    topic: "Automatización",
    type: "theory",
    question: "¿Qué es un sistema SCADA?",
    options: [
      "Un lenguaje de programación para robots",
      "Un sistema de Supervisión, Control y Adquisición de Datos",
      "Un tipo de sensor de temperatura",
      "Una base de datos industrial",
    ],
    correct: 1,
    explanation: "SCADA (Supervisory Control And Data Acquisition) es un sistema que permite supervisar y controlar procesos industriales de forma remota, adquiriendo datos en tiempo real de sensores y actuadores.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 102,
    topic: "Automatización",
    type: "theory",
    question: "¿Qué es un PLC?",
    options: [
      "Un Procesador Lógico Computarizado",
      "Un Controlador Lógico Programable",
      "Un Protocolo de Línea de Comunicación",
      "Un Panel de Luz Central",
    ],
    correct: 1,
    explanation: "PLC (Programmable Logic Controller - Controlador Lógico Programable) es un dispositivo electrónico industrial diseñado para automatizar procesos. Se programa para controlar maquinaria y procesos industriales.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 103,
    topic: "Automatización",
    type: "theory",
    question: "¿Cuál es la función principal de un actuador en un sistema automatizado?",
    options: [
      "Medir variables del proceso",
      "Almacenar datos en la nube",
      "Convertir señales de control en acción física (movimiento, calor, etc.)",
      "Programar el PLC",
    ],
    correct: 2,
    explanation: "Un actuador convierte una señal de control (eléctrica, neumática, hidráulica) en una acción física. Ejemplos: motores, válvulas, pistones, relés. Es el 'brazo ejecutor' del sistema automatizado.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 104,
    topic: "Instrumentación",
    type: "theory",
    question: "¿Qué mide un caudalímetro?",
    options: [
      "La presión de un fluido",
      "La temperatura de un proceso",
      "El caudal (flujo) de un fluido por una tubería",
      "La viscosidad de un líquido",
    ],
    correct: 2,
    explanation: "Un caudalímetro mide el caudal, es decir, la cantidad de fluido (líquido o gas) que pasa por un punto de una tubería en un tiempo determinado. Se mide en litros/minuto, m³/hora, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 105,
    topic: "Instrumentación",
    type: "theory",
    question: "¿Qué tipo de señal estándar se usa en la industria para transmitir datos de sensores?",
    options: [
      "0 a 5V DC solamente",
      "4 a 20 mA (miliamperes)",
      "Señal WiFi",
      "Señal de radio FM",
    ],
    correct: 1,
    explanation: "La señal estándar industrial es de 4 a 20 mA. Se usa porque es resistente al ruido eléctrico, puede viajar largas distancias por cable, y el valor de 4 mA como mínimo permite detectar cables cortados (0 mA = falla).",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 106,
    topic: "Control",
    type: "theory",
    question: "¿Qué es un lazo de control cerrado (feedback)?",
    options: [
      "Un sistema donde el operador controla todo manualmente",
      "Un sistema que mide la salida, la compara con el valor deseado y ajusta automáticamente",
      "Un circuito eléctrico sin resistencias",
      "Una tubería cerrada sin válvulas",
    ],
    correct: 1,
    explanation: "En un lazo cerrado (feedback), el sistema mide la variable de salida con un sensor, la compara con el setpoint (valor deseado) y el controlador ajusta el actuador para corregir el error. Es la base de la automatización.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 107,
    topic: "Control",
    type: "theory",
    question: "En un controlador PID, ¿qué significa la 'P' (acción proporcional)?",
    options: [
      "Actúa proporcionalmente a la velocidad del proceso",
      "Actúa proporcionalmente al error actual entre setpoint y variable medida",
      "Programa el PLC proporcionalmente",
      "Prende y apaga el actuador periódicamente",
    ],
    correct: 1,
    explanation: "La acción Proporcional genera una salida de control proporcional al error actual (diferencia entre setpoint y variable medida). A mayor error, mayor corrección. Es la acción más básica del PID.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 108,
    topic: "Seguridad",
    type: "theory",
    question: "¿Qué es un paro de emergencia (E-STOP)?",
    options: [
      "Un botón que apaga solo las luces del tablero",
      "Un dispositivo que detiene inmediatamente la máquina ante una situación de peligro",
      "Un programa que reinicia el PLC",
      "Una alarma sonora",
    ],
    correct: 1,
    explanation: "El paro de emergencia (E-STOP) es un dispositivo de seguridad que detiene inmediatamente todo el proceso o máquina. Es obligatorio en toda instalación industrial y debe ser accesible y visible (rojo sobre amarillo).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 109,
    topic: "Electricidad",
    type: "theory",
    question: "¿Cuál es la diferencia entre corriente alterna (CA) y corriente continua (CC)?",
    options: [
      "La CA es más peligrosa, la CC no",
      "En la CA la corriente cambia de dirección periódicamente, en la CC fluye siempre en el mismo sentido",
      "La CA solo se usa en baterías",
      "No hay diferencia, son iguales",
    ],
    correct: 1,
    explanation: "La corriente alterna (CA/AC) cambia de dirección cíclicamente (ej: 50 Hz en Argentina). La corriente continua (CC/DC) fluye siempre en la misma dirección. La red eléctrica usa CA; las baterías y electrónica usan CC.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 110,
    topic: "Electricidad",
    type: "theory",
    question: "¿Qué ley establece que V = I × R?",
    options: [
      "Ley de Newton",
      "Ley de Ohm",
      "Ley de Faraday",
      "Ley de Kirchhoff",
    ],
    correct: 1,
    explanation: "La Ley de Ohm establece que el voltaje (V) es igual a la corriente (I) multiplicada por la resistencia (R). Es fundamental en electricidad y electrónica. V se mide en Volts, I en Amperes, R en Ohms.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 111,
    topic: "Neumática",
    type: "theory",
    question: "¿Qué es un cilindro neumático de doble efecto?",
    options: [
      "Un cilindro que funciona con electricidad y agua",
      "Un cilindro que usa aire comprimido para mover el pistón en ambas direcciones",
      "Un cilindro que solo empuja pero no retrae",
      "Un cilindro que almacena aire para uso posterior",
    ],
    correct: 1,
    explanation: "Un cilindro neumático de doble efecto usa aire comprimido para mover el pistón tanto en avance como en retroceso. A diferencia del simple efecto (que usa un resorte para retornar), el doble efecto tiene fuerza en ambos sentidos.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 112,
    topic: "Redes",
    type: "theory",
    question: "¿Qué protocolo de comunicación industrial se usa frecuentemente para conectar PLCs y sensores?",
    options: [
      "HTTP",
      "Modbus",
      "Bluetooth",
      "SMTP",
    ],
    correct: 1,
    explanation: "Modbus es un protocolo de comunicación serial muy usado en la industria para conectar dispositivos como PLCs, sensores e instrumentos. Puede funcionar sobre cable serial (RS-485) o sobre Ethernet (Modbus TCP).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 113,
    topic: "Automatización",
    type: "theory",
    question: "¿Qué es un HMI?",
    options: [
      "Un Hardware de Memoria Interna",
      "Una Interfaz Humano-Máquina (pantalla de operador)",
      "Un Historial de Mantenimiento Industrial",
      "Un módulo de comunicación Ethernet",
    ],
    correct: 1,
    explanation: "HMI (Human-Machine Interface) es la pantalla o panel que permite al operador interactuar con el sistema automatizado: ver datos del proceso, cambiar setpoints, activar/desactivar equipos, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 114,
    topic: "Seguridad",
    type: "theory",
    question: "¿Qué significan las siglas EPP?",
    options: [
      "Equipo de Programación de PLCs",
      "Elemento de Protección Personal",
      "Estación de Procesamiento Principal",
      "Esquema de Proceso Productivo",
    ],
    correct: 1,
    explanation: "EPP (Elementos de Protección Personal) son los equipos que protegen al trabajador de riesgos laborales: casco, guantes, lentes de seguridad, zapatos de seguridad, protección auditiva, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 115,
    topic: "Instrumentación",
    type: "theory",
    question: "¿Qué es la calibración de un instrumento de medición?",
    options: [
      "Pintar el instrumento para que se vea mejor",
      "Comparar las mediciones del instrumento con un patrón de referencia y ajustarlo",
      "Conectar el instrumento a Internet",
      "Instalar el instrumento en el tablero",
    ],
    correct: 1,
    explanation: "Calibrar un instrumento es comparar sus lecturas con un patrón de referencia conocido y, si hay desviaciones, ajustarlo para que mida correctamente. Es fundamental para mantener la calidad y seguridad del proceso.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 116,
    topic: "Control",
    type: "theory",
    question: "¿Qué es el setpoint (punto de ajuste) en un sistema de control?",
    options: [
      "El valor máximo que puede alcanzar el sensor",
      "El valor deseado al que se quiere mantener la variable del proceso",
      "La marca del controlador",
      "El cable que conecta el sensor al PLC",
    ],
    correct: 1,
    explanation: "El setpoint (SP) es el valor deseado o de referencia. El controlador compara el setpoint con la variable de proceso (PV) medida por el sensor y actúa para que la PV se mantenga lo más cerca posible del SP.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 117,
    topic: "Automatización",
    type: "theory",
    question: "¿Cuáles son las 3 partes fundamentales de un sistema de control automático?",
    options: [
      "Monitor, teclado y mouse",
      "Sensor, controlador y actuador",
      "Cable, enchufe y transformador",
      "PLC, HMI y SCADA",
    ],
    correct: 1,
    explanation: "Todo sistema de control tiene: SENSOR (mide la variable), CONTROLADOR (procesa y decide) y ACTUADOR (ejecuta la acción). Ejemplo: termómetro (sensor), termostato (controlador), calefactor (actuador).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 118,
    topic: "Electricidad",
    type: "theory",
    question: "¿Qué dispositivo protege un circuito eléctrico contra sobrecargas?",
    options: [
      "Un capacitor",
      "Un termistor",
      "Un interruptor termomagnético (llave térmica)",
      "Un transformador",
    ],
    correct: 2,
    explanation: "El interruptor termomagnético (llave térmica) protege contra sobrecargas y cortocircuitos, desconectando automáticamente el circuito cuando la corriente supera el valor nominal. Es esencial en toda instalación eléctrica.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 119,
    topic: "Automatización",
    type: "theory",
    question: "¿Qué es la Industria 4.0?",
    options: [
      "La cuarta fábrica más grande del mundo",
      "La cuarta revolución industrial basada en IoT, big data, IA y automatización avanzada",
      "Un modelo de PLC específico",
      "Una norma de seguridad eléctrica",
    ],
    correct: 1,
    explanation: "La Industria 4.0 o cuarta revolución industrial integra tecnologías como IoT (Internet de las Cosas), inteligencia artificial, big data, robótica y cloud computing para crear fábricas inteligentes y conectadas.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 120,
    topic: "Instrumentación",
    type: "theory",
    question: "¿Qué es una termocupla (termopar)?",
    options: [
      "Un motor eléctrico para calentar agua",
      "Un sensor de temperatura que genera un voltaje proporcional a la temperatura",
      "Un interruptor que enciende a cierta temperatura",
      "Un cable especial para redes industriales",
    ],
    correct: 1,
    explanation: "Una termocupla es un sensor de temperatura formado por dos metales diferentes unidos. Genera un pequeño voltaje (mV) proporcional a la diferencia de temperatura. Es muy usada en la industria por su amplio rango y robustez.",
    timeLimit: 25,
    points: 150,
  },
];
