// lib/quizzes/escuela.ts
// Quiz de interés general sobre la escuela técnica
import { Question } from "../questions";

export const ESCUELA_QUESTIONS: Question[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // CONOCIMIENTO GENERAL - CULTURA ESCOLAR Y TÉCNICA
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 301,
    topic: "Cultura General",
    type: "theory",
    question: "¿Cuál es el día del estudiante en Argentina?",
    options: [
      "25 de mayo",
      "21 de septiembre",
      "15 de noviembre",
      "1 de marzo",
    ],
    correct: 1,
    explanation: "El 21 de septiembre se celebra el Día del Estudiante en Argentina, coincidiendo con el inicio de la primavera y en homenaje al traslado de los restos de Domingo Faustino Sarmiento.",
    timeLimit: 15,
    points: 100,
  },
  {
    id: 302,
    topic: "Educación Técnica",
    type: "theory",
    question: "¿Cuántos años dura una tecnicatura de nivel superior en Argentina?",
    options: [
      "1 año",
      "2 años",
      "3 años",
      "5 años",
    ],
    correct: 2,
    explanation: "Las tecnicaturas de nivel superior generalmente duran entre 2 y 3 años, y otorgan un título de Técnico Superior. Combinan formación teórica con práctica profesionalizante.",
    timeLimit: 15,
    points: 100,
  },
  {
    id: 303,
    topic: "Cultura General",
    type: "theory",
    question: "¿Qué día se celebra el Día de la Educación Técnica en Argentina?",
    options: [
      "15 de noviembre",
      "11 de septiembre",
      "17 de agosto",
      "25 de mayo",
    ],
    correct: 0,
    explanation: "El 15 de noviembre se celebra el Día de la Educación Técnica en Argentina, en conmemoración de la fundación de las primeras escuelas de artes y oficios, a través de la Ley N° 1420.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 304,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué significa IoT?",
    options: [
      "Internet of Things (Internet de las Cosas)",
      "Internal Operating Technology",
      "Input-Output Terminal",
      "Integrated Online Tool",
    ],
    correct: 0,
    explanation: "IoT (Internet of Things / Internet de las Cosas) se refiere a objetos físicos conectados a Internet que pueden enviar y recibir datos: sensores, electrodomésticos inteligentes, wearables, vehículos, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 305,
    topic: "Ciencia",
    type: "theory",
    question: "¿Cuál es la unidad de medida de la energía eléctrica que consumimos en nuestras casas?",
    options: [
      "Watts (W)",
      "Kilowatt-hora (kWh)",
      "Amperes (A)",
      "Volts (V)",
    ],
    correct: 1,
    explanation: "La energía eléctrica se mide en kWh (kilowatt-hora). Es la energía consumida por un dispositivo de 1 kW durante 1 hora. Es lo que factura la empresa de electricidad. El Watt es potencia, no energía.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 306,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué es la inteligencia artificial (IA)?",
    options: [
      "Un robot con forma humana",
      "La capacidad de una máquina para simular procesos de inteligencia humana como aprender y razonar",
      "Un programa de computadora muy grande",
      "Una red social para científicos",
    ],
    correct: 1,
    explanation: "La IA es la simulación de procesos de inteligencia humana por máquinas: aprendizaje (machine learning), razonamiento, percepción y procesamiento del lenguaje natural. No necesita un cuerpo físico de robot.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 307,
    topic: "Ciencia",
    type: "theory",
    question: "¿Qué es la energía renovable?",
    options: [
      "Energía que se obtiene solo del petróleo",
      "Energía que proviene de fuentes naturales inagotables o que se regeneran",
      "Energía que se descubrió recientemente",
      "Energía nuclear",
    ],
    correct: 1,
    explanation: "Las energías renovables provienen de fuentes naturales que se regeneran: solar (sol), eólica (viento), hidráulica (agua), geotérmica (calor de la tierra) y biomasa. Son clave para combatir el cambio climático.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 308,
    topic: "Cultura General",
    type: "theory",
    question: "¿Qué es un proyecto integrador en la educación técnica?",
    options: [
      "Un examen escrito de todas las materias",
      "Un trabajo que integra conocimientos de varias materias para resolver un problema real",
      "Una clase magistral del director",
      "Un viaje de estudios a una fábrica",
    ],
    correct: 1,
    explanation: "El proyecto integrador combina conocimientos de múltiples materias para diseñar y construir una solución a un problema real. Desarrolla competencias técnicas, trabajo en equipo, investigación y presentación.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 309,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué es un código QR?",
    options: [
      "Un tipo de virus informático",
      "Un código de barras bidimensional que almacena información legible por cámara",
      "Un lenguaje de programación",
      "Un formato de imagen",
    ],
    correct: 1,
    explanation: "QR (Quick Response) es un código de barras 2D que almacena URLs, texto, contactos, etc. Se escanea con la cámara del celular. Fue inventado en 1994 por Denso Wave (Japón) y se usa masivamente.",
    timeLimit: 15,
    points: 100,
  },
  {
    id: 310,
    topic: "Ciencia",
    type: "theory",
    question: "¿Cuántos bytes tiene 1 Megabyte (MB)?",
    options: [
      "1.000 bytes",
      "100.000 bytes",
      "1.000.000 bytes (un millón)",
      "1.000.000.000 bytes (mil millones)",
    ],
    correct: 2,
    explanation: "1 MB = 1.000.000 bytes (en la convención decimal). En informática, 1 MiB (Mebibyte) = 1.048.576 bytes (2^20). La jerarquía es: Byte → KB → MB → GB → TB.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 311,
    topic: "Educación Técnica",
    type: "theory",
    question: "¿Qué es una práctica profesionalizante?",
    options: [
      "Un examen teórico muy difícil",
      "Una actividad formativa que acerca al estudiante al ejercicio real de su profesión",
      "Un juego recreativo en la escuela",
      "Una reunión de padres",
    ],
    correct: 1,
    explanation: "Las prácticas profesionalizantes son experiencias formativas en las que el estudiante aplica sus conocimientos en situaciones reales o simuladas del mundo laboral. Pueden realizarse en la escuela, empresas o instituciones.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 312,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué es la computación en la nube (cloud computing)?",
    options: [
      "Usar computadoras que flotan en el aire",
      "Acceder a servicios de procesamiento, almacenamiento y software a través de Internet",
      "Programar solo cuando llueve",
      "Un tipo especial de WiFi",
    ],
    correct: 1,
    explanation: "Cloud computing permite usar servidores remotos a través de Internet para almacenar datos, ejecutar programas y procesar información sin necesidad de tener todo en tu propia computadora. Ejemplos: Google Drive, AWS, Azure.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 313,
    topic: "Ciencia",
    type: "theory",
    question: "¿Qué gas representa aproximadamente el 78% de la atmósfera terrestre?",
    options: [
      "Oxígeno",
      "Dióxido de carbono",
      "Nitrógeno",
      "Hidrógeno",
    ],
    correct: 2,
    explanation: "La atmósfera terrestre se compone aproximadamente de: 78% Nitrógeno (N₂), 21% Oxígeno (O₂), y el 1% restante incluye argón, CO₂ y otros gases. El nitrógeno se usa industrialmente en soldadura, neumática, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 314,
    topic: "Cultura General",
    type: "theory",
    question: "¿Qué significa la sigla INET?",
    options: [
      "Instituto Nacional de Empresas Técnicas",
      "Instituto Nacional de Educación Tecnológica",
      "Investigación Nacional en Electrónica y Tecnología",
      "Instituto Nacional de Energía y Transporte",
    ],
    correct: 1,
    explanation: "INET (Instituto Nacional de Educación Tecnológica) es el organismo del Ministerio de Educación de Argentina que regula, fortalece y promueve la educación técnico-profesional en todo el país.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 315,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué es una impresora 3D?",
    options: [
      "Una impresora que imprime fotos en alta resolución",
      "Una máquina que crea objetos tridimensionales capa por capa a partir de un modelo digital",
      "Una impresora que usa tres colores de tinta",
      "Un escáner que digitaliza objetos",
    ],
    correct: 1,
    explanation: "La impresión 3D (fabricación aditiva) construye objetos tridimensionales depositando material capa por capa según un diseño digital (CAD). Se usan plásticos (PLA, ABS), resinas, metales e incluso concreto.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 316,
    topic: "Ciencia",
    type: "theory",
    question: "¿Cuáles son los 3 estados de la materia más comunes?",
    options: [
      "Caliente, tibio y frío",
      "Sólido, líquido y gaseoso",
      "Plástico, metal y madera",
      "Pesado, ligero y medio",
    ],
    correct: 1,
    explanation: "Los 3 estados clásicos de la materia son: sólido (forma y volumen definidos), líquido (volumen definido, forma variable) y gaseoso (ni forma ni volumen definidos). También existe el plasma (4° estado).",
    timeLimit: 15,
    points: 100,
  },
  {
    id: 317,
    topic: "Educación Técnica",
    type: "theory",
    question: "¿Qué es un plano técnico?",
    options: [
      "Una foto de la pieza terminada",
      "Un dibujo con medidas exactas, escalas y normas que permite fabricar o construir algo",
      "Un resumen del proyecto en texto",
      "Una lista de materiales",
    ],
    correct: 1,
    explanation: "Un plano técnico es una representación gráfica normalizada de un objeto, con medidas (cotas), escalas, vistas, secciones y tolerancias que permiten fabricarlo o construirlo correctamente. Se dibuja según normas IRAM/ISO.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 318,
    topic: "Tecnología",
    type: "theory",
    question: "¿Qué es Arduino?",
    options: [
      "Un lenguaje de programación exclusivo",
      "Una plataforma de hardware y software libre para crear proyectos electrónicos",
      "Una marca de computadoras",
      "Un sistema operativo para celulares",
    ],
    correct: 1,
    explanation: "Arduino es una plataforma de código abierto que incluye placas con microcontrolador y un entorno de desarrollo (IDE). Permite crear proyectos electrónicos interactivos de forma accesible. Ideal para aprender electrónica.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 319,
    topic: "Ciencia",
    type: "theory",
    question: "¿Qué mide un manómetro?",
    options: [
      "Temperatura",
      "Presión de un fluido",
      "Velocidad del viento",
      "Nivel de un líquido",
    ],
    correct: 1,
    explanation: "El manómetro mide la presión de fluidos (gases o líquidos). Se usa en compresores, calderas, redes de gas, neumática, etc. La presión se mide en bar, psi, kg/cm², Pascal, entre otras unidades.",
    timeLimit: 15,
    points: 100,
  },
  {
    id: 320,
    topic: "Cultura General",
    type: "theory",
    question: "¿Qué habilidad blanda (soft skill) es más valorada en el trabajo técnico según las empresas?",
    options: [
      "Saber muchos idiomas",
      "Trabajo en equipo y comunicación efectiva",
      "Memorizarlo todo",
      "Llegar siempre primero",
    ],
    correct: 1,
    explanation: "El trabajo en equipo y la comunicación efectiva son las soft skills más valoradas. En un entorno técnico, se trabaja siempre con otros (operadores, ingenieros, supervisores) y comunicar bien evita errores y accidentes.",
    timeLimit: 20,
    points: 100,
  },
];
