// lib/quizzes/mmo.ts
// Quiz sobre la Tecnicatura en Mantenimiento de Máquinas y Obras (MMO)
import { Question } from "../questions";

export const MMO_QUESTIONS: Question[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // MANTENIMIENTO MECÁNICO Y DE OBRAS
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 201,
    topic: "Mantenimiento",
    type: "theory",
    question: "¿Qué tipo de mantenimiento se realiza ANTES de que ocurra una falla?",
    options: [
      "Mantenimiento correctivo",
      "Mantenimiento preventivo",
      "Mantenimiento de emergencia",
      "Mantenimiento estético",
    ],
    correct: 1,
    explanation: "El mantenimiento PREVENTIVO se planifica y ejecuta antes de que la máquina falle, basándose en intervalos de tiempo o uso. Incluye lubricación, cambio de filtros, inspecciones, etc. Reduce paradas no planificadas.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 202,
    topic: "Mantenimiento",
    type: "theory",
    question: "¿Qué es el mantenimiento predictivo?",
    options: [
      "Reparar la máquina cuando se rompe",
      "Monitorear el estado real de la máquina para predecir cuándo va a fallar",
      "Cambiar piezas cada 6 meses sin importar su estado",
      "Pintar y limpiar las máquinas periódicamente",
    ],
    correct: 1,
    explanation: "El mantenimiento predictivo usa técnicas como análisis de vibraciones, termografía y análisis de aceite para monitorear el estado real de la máquina y predecir cuándo va a necesitar intervención, optimizando costos y tiempos.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 203,
    topic: "Mecánica",
    type: "theory",
    question: "¿Para qué sirve un rodamiento (rulemán)?",
    options: [
      "Para sellar tuberías",
      "Para reducir la fricción entre piezas que giran o se deslizan",
      "Para medir la velocidad de un eje",
      "Para conectar cables eléctricos",
    ],
    correct: 1,
    explanation: "Los rodamientos (rulemanes) reducen la fricción entre un eje giratorio y su soporte. Pueden ser de bolas, de rodillos o de agujas. Son esenciales en motores, poleas, ruedas y toda pieza giratoria.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 204,
    topic: "Mecánica",
    type: "theory",
    question: "¿Qué herramienta se usa para medir con precisión de centésimas de milímetro?",
    options: [
      "Regla metálica",
      "Cinta métrica",
      "Calibre o pie de rey (vernier)",
      "Escuadra",
    ],
    correct: 2,
    explanation: "El calibre (también llamado pie de rey o vernier) permite medir diámetros exteriores, interiores y profundidades con precisión de hasta 0.02 mm. Es una herramienta fundamental en cualquier taller mecánico.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 205,
    topic: "Materiales",
    type: "theory",
    question: "¿Qué es el acero inoxidable?",
    options: [
      "Acero pintado con pintura antióxido",
      "Una aleación de hierro con cromo (mínimo ~10.5%) que resiste la corrosión",
      "Acero que nunca se calienta",
      "Un plástico con apariencia metálica",
    ],
    correct: 1,
    explanation: "El acero inoxidable es una aleación de hierro con al menos ~10.5% de cromo. El cromo forma una capa pasiva de óxido de cromo que protege de la corrosión. Se usa en cocinas, industria alimenticia, medicina, etc.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 206,
    topic: "Soldadura",
    type: "theory",
    question: "¿Qué tipo de soldadura usa un electrodo revestido que se consume durante el proceso?",
    options: [
      "Soldadura TIG",
      "Soldadura por arco con electrodo revestido (SMAW / eléctrica)",
      "Soldadura por puntos",
      "Soldadura autógena",
    ],
    correct: 1,
    explanation: "La soldadura SMAW (Shielded Metal Arc Welding), conocida como 'soldadura eléctrica', usa un electrodo revestido que se va consumiendo. El revestimiento genera un gas protector y escoria. Es la más común en mantenimiento.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 207,
    topic: "Hidráulica",
    type: "theory",
    question: "¿Cuál es el principio fundamental de la hidráulica?",
    options: [
      "El aire se comprime fácilmente",
      "La presión aplicada a un fluido confinado se transmite en todas las direcciones (Principio de Pascal)",
      "El agua siempre fluye hacia arriba",
      "Los líquidos no pueden transmitir fuerza",
    ],
    correct: 1,
    explanation: "El Principio de Pascal establece que la presión aplicada a un fluido confinado se transmite íntegramente en todas las direcciones. Esto permite multiplicar fuerzas en prensas hidráulicas, elevadores, retroexcavadoras, etc.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 208,
    topic: "Seguridad",
    type: "theory",
    question: "Antes de trabajar en una máquina, ¿qué procedimiento de seguridad es obligatorio?",
    options: [
      "Solamente avisar al supervisor",
      "Bloqueo y etiquetado (LOTO - Lock Out Tag Out)",
      "Mirar si alguien más está trabajando",
      "Usar guantes solamente",
    ],
    correct: 1,
    explanation: "El procedimiento LOTO (Lock Out Tag Out) es obligatorio. Consiste en desconectar la fuente de energía, bloquearla con candado y colocar una etiqueta identificatoria para que nadie la reenergice mientras se trabaja.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 209,
    topic: "Mecánica",
    type: "theory",
    question: "¿Qué tipo de transmisión mecánica usa una correa y poleas?",
    options: [
      "Transmisión por engranajes",
      "Transmisión por cadena",
      "Transmisión por correa (también llamada por faja)",
      "Transmisión por piñón y cremallera",
    ],
    correct: 2,
    explanation: "La transmisión por correa usa una faja flexible (plana, en V, o dentada) que conecta dos poleas para transmitir movimiento. Permite cierto deslizamiento y absorbe vibraciones. Se usa en compresores, ventiladores, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 210,
    topic: "Electricidad",
    type: "theory",
    question: "¿Qué instrumento se usa para medir voltaje, corriente y resistencia?",
    options: [
      "Osciloscopio",
      "Multímetro (tester)",
      "Pirómetro",
      "Manómetro",
    ],
    correct: 1,
    explanation: "El multímetro (tester) es el instrumento más versátil del electricista. Mide voltaje (V), corriente (A). resistencia (Ω) y, en modelos digitales, también continuidad, capacitancia, frecuencia, etc.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 211,
    topic: "Mantenimiento",
    type: "theory",
    question: "¿Qué es una orden de trabajo (OT) en mantenimiento?",
    options: [
      "Un email del jefe pidiendo que trabajes más rápido",
      "Un documento que detalla el trabajo a realizar, materiales, tiempos y responsables",
      "Un recibo de sueldo",
      "Una cotización de repuestos",
    ],
    correct: 1,
    explanation: "La Orden de Trabajo (OT) es el documento que autoriza y describe una tarea de mantenimiento: qué hacer, dónde, quién lo hace, materiales necesarios, prioridad y tiempos estimados. Es clave para la gestión del mantenimiento.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 212,
    topic: "Materiales",
    type: "theory",
    question: "¿Qué es el torque (par) de apriete?",
    options: [
      "La temperatura a la que se funde un tornillo",
      "La fuerza de giro aplicada a un tornillo o tuerca para ajustarlo correctamente",
      "El diámetro del tornillo",
      "La cantidad de tornillos necesarios",
    ],
    correct: 1,
    explanation: "El torque (par de apriete) es la fuerza de giro aplicada para apretar un tornillo o tuerca. Se mide con torquímetro y se expresa en Nm (Newton-metro). Aplicar el torque correcto evita roturas y aflojamientos.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 213,
    topic: "Mecánica",
    type: "theory",
    question: "¿Para qué se usa la lubricación en las máquinas?",
    options: [
      "Solo para que las piezas brillen",
      "Para reducir fricción, desgaste y temperatura entre piezas en movimiento",
      "Para pintar las piezas de color negro",
      "Para aumentar la velocidad del motor",
    ],
    correct: 1,
    explanation: "La lubricación reduce la fricción entre superficies en movimiento, disminuye el desgaste, disipa calor, protege contra la corrosión y ayuda a sellar. Es una de las tareas más importantes del mantenimiento preventivo.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 214,
    topic: "Construcción",
    type: "theory",
    question: "¿Qué es el hormigón armado?",
    options: [
      "Hormigón mezclado con pintura especial",
      "Hormigón reforzado con barras de acero (armadura) en su interior",
      "Hormigón que se endurece más rápido",
      "Hormigón de color gris oscuro",
    ],
    correct: 1,
    explanation: "El hormigón armado combina hormigón (que resiste bien la compresión) con barras de acero (que resisten bien la tracción). Juntos forman un material versátil usado en columnas, vigas, losas y cimientos.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 215,
    topic: "Seguridad",
    type: "theory",
    question: "¿Qué indica la señalización de color AMARILLO en una planta industrial?",
    options: [
      "Zona segura",
      "Precaución, riesgo o advertencia",
      "Obligación de usar EPP",
      "Prohibido el paso",
    ],
    correct: 1,
    explanation: "El color AMARILLO indica precaución, advertencia o riesgo. El ROJO indica prohibición o peligro, el AZUL indica obligación (ej: usar casco), y el VERDE indica condición segura (ej: salida de emergencia).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 216,
    topic: "Motores",
    type: "theory",
    question: "¿Qué tipo de motor eléctrico es el más utilizado en la industria?",
    options: [
      "Motor de corriente continua",
      "Motor asíncrono trifásico (de inducción)",
      "Motor paso a paso",
      "Motor universal",
    ],
    correct: 1,
    explanation: "El motor asíncrono trifásico (de inducción) es el más usado en la industria por su robustez, bajo costo, poco mantenimiento y alta eficiencia. Se usa en bombas, compresores, ventiladores, cintas transportadoras, etc.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 217,
    topic: "Neumática",
    type: "theory",
    question: "¿Qué equipo genera el aire comprimido en un sistema neumático?",
    options: [
      "Una bomba hidráulica",
      "Un compresor",
      "Un generador eléctrico",
      "Un ventilador industrial",
    ],
    correct: 1,
    explanation: "El compresor aspira aire atmosférico y lo comprime a alta presión (6-8 bar típicamente). El aire comprimido se almacena en un tanque (pulmón) y se distribuye por tuberías a los actuadores neumáticos de la planta.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 218,
    topic: "Mantenimiento",
    type: "theory",
    question: "¿Qué es el análisis de vibraciones en mantenimiento predictivo?",
    options: [
      "Verificar si el piso de la fábrica vibra",
      "Medir y analizar las vibraciones de una máquina para detectar fallas incipientes",
      "Hacer vibrar la máquina para probarla",
      "Un tipo de soldadura especial",
    ],
    correct: 1,
    explanation: "El análisis de vibraciones mide las vibraciones de máquinas rotativas (motores, bombas, ventiladores) para detectar problemas como desbalanceo, desalineación, rodamientos dañados o engranajes gastados ANTES de que fallen.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 219,
    topic: "Mecánica",
    type: "theory",
    question: "¿Qué tipo de rosca se usa comúnmente en plomería y tuberías?",
    options: [
      "Rosca métrica fina",
      "Rosca Whitworth BSP (cónica para sellar)",
      "Rosca cuadrada",
      "Rosca de tornillo sin fin",
    ],
    correct: 1,
    explanation: "La rosca BSP (British Standard Pipe) es la más usada en tuberías y conexiones de plomería. Su versión cónica (BSPT) permite sellar sin cinta teflón en algunos casos, ya que la conicidad genera un ajuste hermético.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 220,
    topic: "Construcción",
    type: "theory",
    question: "¿Qué es un nivel de burbuja y para qué se usa?",
    options: [
      "Para medir la temperatura del agua",
      "Para verificar si una superficie está horizontal o vertical (a plomo)",
      "Para medir la presión del aire",
      "Para cortar materiales rectos",
    ],
    correct: 1,
    explanation: "El nivel de burbuja es una herramienta que usa un tubo con líquido y una burbuja de aire. Cuando la burbuja está centrada entre las marcas, la superficie está perfectamente horizontal (o vertical, según el uso).",
    timeLimit: 20,
    points: 100,
  },
];
