import { Question } from "../questions";

export const PROG_GENERAL_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "Algoritmos",
    type: "theory",
    question: "¿Qué es un algoritmo en programación?",
    options: [
      "Un hardware específico para resolver cuentas",
      "Una serie de pasos finitos y ordenados para resolver un problema",
      "El código fuente de un programa compilado",
      "La memoria RAM utilizada por un programa",
    ],
    correct: 1,
    explanation: "Un algoritmo es la receta o secuencia de pasos lógicos que permiten llegar a la solución de un problema, independientemente del lenguaje de programación.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 2,
    topic: "Paradigma Imperativo",
    type: "theory",
    question: "¿Qué rol cumplen las variables e iteraciones en la programación imperativa?",
    options: [
      "Modificar el estado del programa paso a paso indicando el cómo llegar al resultado",
      "Solo se utilizan para comunicarse con la base de datos",
      "Definir únicamente reglas lógicas sin modificar ningún estado",
      "Generar objetos físicos a partir de clases",
    ],
    correct: 0,
    explanation: "En la programación imperativa, damos órdenes detalladas (comandos) y modificamos el estado del programa a través de variables e iteraciones.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 3,
    topic: "Programación Estructurada",
    type: "theory",
    question: "La modularización de un programa permite:",
    options: [
      "Escribir todo el código en un único bloque continuo",
      "Evitar el uso de lenguajes compilados",
      "Dividir un problema en subproblemas (funciones o procedimientos) más fáciles de resolver y mantener",
      "Hacer que el programa corra sin usar memoria",
    ],
    correct: 2,
    explanation: "Modularizar (o dividir y vencerás) mejora la legibilidad, reduce la repetición y facilita el mantenimiento del código.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 4,
    topic: "Estructuras de Control",
    type: "code",
    language: "python",
    question: "¿Cuántas veces se ejecutará el código dentro de esta estructura iterativa?",
    code: `contador = 0\nwhile contador < 3:\n    print("Hola")\n    contador += 1`,
    options: ["1 vez", "2 veces", "3 veces", "4 veces"],
    correct: 2,
    explanation: "El contador empieza en 0. Imprime y suma (1), imprime y suma (2), imprime y suma (3). Luego la condición (3 < 3) es falsa, por lo que se ejecuta exactamente 3 veces.",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 5,
    topic: "Funciones",
    type: "theory",
    question: "Al definir una función, los 'parámetros' sirven para:",
    options: [
      "Recibir datos de entrada que la función necesita para realizar su tarea",
      "Retornar siempre un valor True o False",
      "Manejar los errores de compilación",
      "Borrar variables de la memoria",
    ],
    correct: 0,
    explanation: "Los parámetros son variables locales de la función que reciben los valores (argumentos) que se le pasan al invocarla.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 6,
    topic: "Paradigma Funcional",
    type: "theory",
    question: "En una función recursiva pura, la 'condición de terminación' (o caso base) es fundamental porque:",
    options: [
      "Acelera el procesador al doble",
      "Evita que la función se llame a sí misma infinitamente",
      "Permite usar bases de datos SQL",
      "Convierte la función a paradigma orientado a objetos",
    ],
    correct: 1,
    explanation: "Si no hay caso base o condición de corte, la recursión no se detiene nunca y termina agotando la memoria (Stack Overflow).",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 7,
    topic: "Tipos de Datos",
    type: "theory",
    question: "¿Qué característica principal tiene un 'Arreglo' (Lista/Array)?",
    options: [
      "Almacena un solo valor constante",
      "Almacena una colección secuencial de elementos accesibles mediante un índice",
      "Es exclusivo del paradigma orientado a objetos",
      "Acelera el tiempo de compilación del código",
    ],
    correct: 1,
    explanation: "Un arreglo o lista guarda múltiples valores en orden, y podemos acceder a ellos usando su posición (índice), que generalmente arranca en 0.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 8,
    topic: "POO",
    type: "theory",
    question: "En POO, ¿cuál es la relación correcta entre Clase y Objeto?",
    options: [
      "La Clase es la instancia en memoria, el Objeto es el archivo de texto",
      "Son sinónimos exactos en todos los lenguajes",
      "La Clase es el molde genérico, y el Objeto es una instancia concreta creada a partir de esa clase",
      "El Objeto crea a las Clases mediante herencia",
    ],
    correct: 2,
    explanation: "Las Clases definen qué atributos y métodos tendrán las cosas, pero los Objetos son esas cosas ya creadas y viviendo en la memoria (los planos vs. la casa).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 9,
    topic: "POO: Mensajes y Métodos",
    type: "theory",
    question: "¿Qué es un 'método' dentro del paradigma orientado a objetos?",
    options: [
      "Un bloque de código estructurado fuera de cualquier clase",
      "El proceso de instalación de un software",
      "Un comportamiento o función que pertenece a un objeto y es invocado mediante un mensaje",
      "Un tipo especial de variable para guardar texto",
    ],
    correct: 2,
    explanation: "Los métodos son las rutinas que definen qué sabe hacer un objeto. Otros objetos se comunican con él enviándole 'mensajes' para ejecutar esos métodos.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 10,
    topic: "POO: Polimorfismo",
    type: "theory",
    question: "El polimorfismo permite que:",
    options: [
      "Dos objetos de clases distintas respondan de manera diferente al mismo mensaje",
      "Un programa se ejecute en Windows y en Linux sin esfuerzo",
      "Se borre código duplicado de forma automática",
      "Las iteraciones corran en paralelo",
    ],
    correct: 0,
    explanation: "Polimorfismo significa 'múltiples formas'. Permite usar objetos de distintos tipos con la misma interfaz (mismo mensaje), pero que cada uno actúe como corresponda.",
    timeLimit: 25,
    points: 150,
  },
];
