import { Question } from "../questions";

export const PROG_ESTRUCTURADA_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "Algoritmos",
    type: "theory",
    question: "¿Qué son la 'precondición' y 'postcondición' en la especificación de un programa?",
    options: [
      "Son librerías que se deben pre-instalar antes de codificar",
      "La precondición es el estado inicial válido requerido, y la postcondición es qué garantiza el algoritmo al finalizar",
      "Refieren únicamente a la compatibilidad del tipo de computadora",
      "Son tipos de bucles infinitos no deseados",
    ],
    correct: 1,
    explanation: "Se usan como 'contrato': Si cumplís la precondición al llamar a la función (los datos están bien), te aseguro que el resultado cumplirá la postcondición (respuesta correcta).",
    timeLimit: 25,
    points: 150,
  },
  {
    id: 2,
    topic: "Estructuras Básicas",
    type: "theory",
    question: "¿Cuáles son las tres estructuras de control fundamentales en la programación estructurada?",
    options: [
      "Secuencia, Selección e Iteración",
      "Clases, Objetos y Métodos",
      "Sumar, Restar y Dividir",
      "Filtros, Mapas y Reducciones",
    ],
    correct: 0,
    explanation: "El paradigma estructurado indica que cualquier algoritmo puede programarse combinando Secuencias (un paso tras otro), Selecciones (if/else) e Iteraciones (while/for).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 3,
    topic: "Variables y Estado",
    type: "theory",
    question: "¿Qué es el 'estado' en el paradigma imperativo?",
    options: [
      "La versión del sistema operativo actual",
      "Si el programa está encendido o apagado",
      "El conjunto de todos los valores que tienen las variables del programa en un momento dado",
      "El país desde el que se accede al programa",
    ],
    correct: 2,
    explanation: "El paradigma imperativo actúa 'cambiando el estado'. Cada paso modifica el valor de una variable, mutando el estado general hasta llegar al resultado final.",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 4,
    topic: "Diseño de Algoritmos",
    type: "theory",
    question: "Una 'iteración' es útil en el diseño de un algoritmo cuando...",
    options: [
      "Necesitamos evitar el uso total de variables",
      "Queremos repetir un bloque de código automáticamente mientras se cumpla una condición",
      "Solo tenemos que tomar una decisión de Sí o No inmediata",
      "Precisamos crear un nuevo objeto derivado de otra clase",
    ],
    correct: 1,
    explanation: "Las iteraciones o bucles evitan que tengamos que repetir el código manualmente. La computadora lo ejecuta reiteradas veces según nuestra lógica (ej. procesar a 30 alumnos).",
    timeLimit: 20,
    points: 100,
  },
  {
    id: 5,
    topic: "Diseño de Algoritmos",
    type: "code",
    language: "python",
    question: "En este diagrama o fragmento condicional, ocurre una SELECCIÓN. ¿Qué imprime si la nota es 7?",
    code: `nota = 7\nif nota >= 7:\n    print("Aprobado")\nelse:\n    print("Desaprobado")`,
    options: [
      "Desaprobado",
      "Error, faltan datos",
      "No imprime nada",
      "Aprobado",
    ],
    correct: 3,
    explanation: "El código evalúa si 'nota >= 7'. Como 7 es igual a 7, la condición da VERDADERO (True) y entra a la rama positiva de la selección, imprimiendo 'Aprobado'.",
    timeLimit: 20,
    points: 100,
  },
];
